version: '2'
services:
    gw-app:
        image: gw
        external_links:
            - gw-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - gw-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gw
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    gw-postgresql:
        extends:
            file: postgresql.yml
            service: gw-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra.yml
        #     service: gw-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
